<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_find_service_centre</name>
   <tag></tag>
   <elementGuidId>5e165afb-10e6-4b6d-b9d2-5fffb20bcf91</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='block-content']/div/div/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.button.button--large.button--primary.is-internal</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8c9bdcf0-92ff-41e3-856c-7eb747132989</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/service-centre</value>
      <webElementGuid>0749175d-441f-44ff-af5e-04dfe76d23e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>fixedCtaMessage</value>
      <webElementGuid>1b45dfac-aa36-4003-8a84-692b2e2a8070</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button button--large button--primary is-internal</value>
      <webElementGuid>a1476dbc-8697-4da4-832d-da979bee818c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3b9b0fce-20dc-4de9-859a-10e7274d5694</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Find a service centre</value>
      <webElementGuid>16f25233-a461-47e5-a7fe-869caacda5f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;block-content&quot;)/div[@class=&quot;fixed-cta&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;fixed-cta__action&quot;]/a[@class=&quot;button button--large button--primary is-internal&quot;]</value>
      <webElementGuid>4d71b5fc-28b9-4274-9e69-f1c6a30f18dc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='block-content']/div/div/div/a</value>
      <webElementGuid>a040dda8-9bab-422b-9a87-1e5bf871cbaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Find a service centre')]</value>
      <webElementGuid>9b0db72b-c48c-4213-9b9b-7f9230730ed9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Share'])[1]/following::a[6]</value>
      <webElementGuid>38818983-e8ca-4830-b522-4e497e3c225a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Print'])[1]/following::a[6]</value>
      <webElementGuid>ad642a92-65e0-40ae-852c-a303a73c27ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Was the information on this page useful?'])[1]/preceding::a[1]</value>
      <webElementGuid>5e4bb540-af7a-4daa-9ef7-e934ca5fa78d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Yes'])[1]/preceding::a[1]</value>
      <webElementGuid>d429e30a-59c7-4ce8-9aab-574a5c9e6b31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Find a service centre']/parent::*</value>
      <webElementGuid>e4a4d19e-a86d-41cf-9e4b-72f3f8bdc2e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/service-centre')])[3]</value>
      <webElementGuid>5ffe46d5-8458-4f17-8308-531ff251adff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/a</value>
      <webElementGuid>3270e795-d0b8-47d5-84a8-ba2508a6a279</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/service-centre' and (text() = 'Find a service centre' or . = 'Find a service centre')]</value>
      <webElementGuid>20026bf6-7543-48e7-909d-83ef62fe93fa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
