<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_search_number</name>
   <tag></tag>
   <elementGuidId>9f563afa-5be7-45eb-bd08-5d51ad6fb445</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='search']/div/div/div/h3/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h3 > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4224fc16-1b92-4b32-824e-4911ff319317</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.sajari.com/token/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwdXJwb3NlIjoiY2xpY2siLCJkZXN0aW5hdGlvbiI6Imh0dHBzOi8vd3d3LnNlcnZpY2UubnN3Lmdvdi5hdS90cmFuc2FjdGlvbi9hcHBseS1jb2xsZWN0LW51bWJlci1wbGF0ZXMtYW5vdGhlci1zZXJ2aWNlLWNlbnRyZSIsInZhbHMiOnsiY29sbGVjdGlvbiI6WyJzZXJ2aWNlbnN3Il0sImNvbXBhbnkiOlsiMTU2MDQxMDMzMzUzODA2ODQzMCJdLCJmaWVsZCI6WyJ1cmwiXSwicHJvamVjdCI6WyIxNTYwNDEwMzMzNTM4MDY4NDMwIl0sInEuaWQiOlsiNmF5emlmbzhsYTFiMTdndCJdLCJxLnNsIjpbIjEiXSwicS51aWQiOlsiNmF5emlmbzhsYTFiMTdndDAiXSwidmFsdWUiOlsiaHR0cHM6Ly93d3cuc2VydmljZS5uc3cuZ292LmF1L3RyYW5zYWN0aW9uL2FwcGx5LWNvbGxlY3QtbnVtYmVyLXBsYXRlcy1hbm90aGVyLXNlcnZpY2UtY2VudHJlIl19fQ.dYBXekGHJUWER8ZFFBbVTS35BVT05pRaAcxwaXE9gSU</value>
      <webElementGuid>da6ea472-bb37-40e0-a9a3-89c3fd7998a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Apply to collect number plates from another service centre</value>
      <webElementGuid>7f90b0c7-eae5-43a0-bdab-324d67079acb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;search&quot;)/div[@class=&quot;search&quot;]/div[@class=&quot;search__results&quot;]/div[@class=&quot;search__result&quot;]/h3[1]/a[1]</value>
      <webElementGuid>dce56067-d462-40ce-8307-3eaf65bbda3e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='search']/div/div/div/h3/a</value>
      <webElementGuid>da0fd20d-d138-46e3-b36c-f255944a320e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Apply to collect number plates from another service centre')]</value>
      <webElementGuid>dd59d86a-56e3-4ebd-840a-02dfe4286f72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search'])[2]/following::a[1]</value>
      <webElementGuid>2b279951-c813-460b-bc71-87e1ef7db4fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[3]/following::a[1]</value>
      <webElementGuid>d924bd6d-f52c-449a-990f-1341d51d5f8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apply to exchange existing number plates between vehicles'])[1]/preceding::a[1]</value>
      <webElementGuid>10f37bd0-8082-44e6-8d5c-2ad4079520cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apply for a Dealer Vehicle Registration Scheme (DVRS) agreement'])[1]/preceding::a[2]</value>
      <webElementGuid>0cc0054b-0caf-4d75-afe0-9425a51b42b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Apply to collect number plates from another service centre']/parent::*</value>
      <webElementGuid>1071e0c9-6cb4-4af6-9ecf-1d8084ea5c5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.sajari.com/token/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwdXJwb3NlIjoiY2xpY2siLCJkZXN0aW5hdGlvbiI6Imh0dHBzOi8vd3d3LnNlcnZpY2UubnN3Lmdvdi5hdS90cmFuc2FjdGlvbi9hcHBseS1jb2xsZWN0LW51bWJlci1wbGF0ZXMtYW5vdGhlci1zZXJ2aWNlLWNlbnRyZSIsInZhbHMiOnsiY29sbGVjdGlvbiI6WyJzZXJ2aWNlbnN3Il0sImNvbXBhbnkiOlsiMTU2MDQxMDMzMzUzODA2ODQzMCJdLCJmaWVsZCI6WyJ1cmwiXSwicHJvamVjdCI6WyIxNTYwNDEwMzMzNTM4MDY4NDMwIl0sInEuaWQiOlsiNmF5emlmbzhsYTFiMTdndCJdLCJxLnNsIjpbIjEiXSwicS51aWQiOlsiNmF5emlmbzhsYTFiMTdndDAiXSwidmFsdWUiOlsiaHR0cHM6Ly93d3cuc2VydmljZS5uc3cuZ292LmF1L3RyYW5zYWN0aW9uL2FwcGx5LWNvbGxlY3QtbnVtYmVyLXBsYXRlcy1hbm90aGVyLXNlcnZpY2UtY2VudHJlIl19fQ.dYBXekGHJUWER8ZFFBbVTS35BVT05pRaAcxwaXE9gSU')]</value>
      <webElementGuid>ad58ba1c-2895-4fc7-9b25-47ac890aee5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h3/a</value>
      <webElementGuid>72e9f24d-27df-4594-a6f3-f4ed48ed72dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.sajari.com/token/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwdXJwb3NlIjoiY2xpY2siLCJkZXN0aW5hdGlvbiI6Imh0dHBzOi8vd3d3LnNlcnZpY2UubnN3Lmdvdi5hdS90cmFuc2FjdGlvbi9hcHBseS1jb2xsZWN0LW51bWJlci1wbGF0ZXMtYW5vdGhlci1zZXJ2aWNlLWNlbnRyZSIsInZhbHMiOnsiY29sbGVjdGlvbiI6WyJzZXJ2aWNlbnN3Il0sImNvbXBhbnkiOlsiMTU2MDQxMDMzMzUzODA2ODQzMCJdLCJmaWVsZCI6WyJ1cmwiXSwicHJvamVjdCI6WyIxNTYwNDEwMzMzNTM4MDY4NDMwIl0sInEuaWQiOlsiNmF5emlmbzhsYTFiMTdndCJdLCJxLnNsIjpbIjEiXSwicS51aWQiOlsiNmF5emlmbzhsYTFiMTdndDAiXSwidmFsdWUiOlsiaHR0cHM6Ly93d3cuc2VydmljZS5uc3cuZ292LmF1L3RyYW5zYWN0aW9uL2FwcGx5LWNvbGxlY3QtbnVtYmVyLXBsYXRlcy1hbm90aGVyLXNlcnZpY2UtY2VudHJlIl19fQ.dYBXekGHJUWER8ZFFBbVTS35BVT05pRaAcxwaXE9gSU' and (text() = 'Apply to collect number plates from another service centre' or . = 'Apply to collect number plates from another service centre')]</value>
      <webElementGuid>fbee63ba-fc65-49ea-afb7-90bcd8b85a15</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
